### ISSUE TITLE
Feature: Mood Buttons

### ISSUE THREAD

**Issue by LoopAM** [LoopAM/mood-track#2]
# Epic Title

Feature: Mood Buttons

## Epic Description

This feature will replace the song search functionality with buttons that will offer predefined moods.

## List of Tasks
- [x] #3 Add button elements
- [x] #4 Add element logic
- [x] #5 Refactor API routes for added functionality
